# Generated by scripts/generate.mjs from glyphs.json — do not edit by hand.
# Run `npm run generate` to regenerate.
# Default entrypoint: Nerd Font glyphs as ICON_* variables.
# Other variants live in zsh/<variant>.zsh; for a custom prefix, text-
# substitute ICON_ (e.g. sed 's/^ICON_/MYPREFIX_ICON_/').

source "${0:A:h}/zsh/nerd.zsh"
