#!/usr/bin/env node
// Reads glyphs.json (name -> codepoint hex) and emits:
//   - src/generated.ts — typed named glyphs + a glyph(name) lookup, escapes
//     written as JS \u{XXXX} by construction (never raw PUA bytes)
//   - glyphs.zsh        — GLYPH_* vars plus SHUI_ICON_* aliases (shui compat),
//     escapes written as zsh $'\U0000XXXX' (normalised 8-hex)
// See plan.md for the full spec.
import { readFileSync, writeFileSync } from "fs"
import { fileURLToPath } from "url"
import { dirname, join } from "path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const glyphs = JSON.parse(readFileSync(join(root, "glyphs.json"), "utf8"))
const names = Object.keys(glyphs).sort()

const camel = (kebab) =>
  kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const upper = (kebab) => kebab.toUpperCase().replace(/-/g, "_")
const banner = (comment) =>
  [
    `${comment} Generated by scripts/generate.mjs from glyphs.json — do not edit by hand.`,
    `${comment} Run \`npm run generate\` to regenerate.`,
  ].join("\n")

// --- TypeScript: src/generated.ts ---
const ts = [
  banner("//"),
  "",
  "export const glyphs = {",
  ...names.map((n) => `  ${camel(n)}: "\\u{${glyphs[n]}}",`),
  "} as const",
  "",
  "export type GlyphName = keyof typeof glyphs",
  "",
  "export const glyph = (name: GlyphName): string => glyphs[name]",
  "",
].join("\n")
writeFileSync(join(root, "src", "generated.ts"), ts)

// --- zsh: glyphs.zsh ---
const zshVar = (prefix, n) =>
  `${prefix}_${upper(n)}=$'\\U${glyphs[n].padStart(8, "0")}'`
const zsh = [
  banner("#"),
  "# Source this file to get GLYPH_* variables (and SHUI_ICON_* aliases).",
  "",
  ...names.map((n) => zshVar("GLYPH", n)),
  "",
  "# shui-compatible aliases",
  ...names.map((n) => zshVar("SHUI_ICON", n)),
  "",
].join("\n")
writeFileSync(join(root, "glyphs.zsh"), zsh)

console.log(
  `Generated src/generated.ts and glyphs.zsh (${names.length} glyphs)`,
)
