#!/usr/bin/env node
// Reads glyphs.json (name -> { nerd?, unicode?, emoji? }) and emits:
//   - src/generated.ts   — typed `glyphs` record, each variant an escaped string
//                          (JS \u{XXXX}, by construction — never raw PUA bytes).
//   - glyphs.plugin.zsh  — a ready-to-source zsh plugin: ICON_* vars, nerd
//                          variant, escapes as $'\U0000XXXX'.
//
// A stored value is either a codepoint hex (nerd/unicode — single scalars, kept
// escape-safe) or a literal emoji string (may be a multi-scalar grapheme
// cluster, emitted verbatim). The prefix is a parameter (default ICON); this
// library names no specific consumer.
import { readFileSync, writeFileSync } from "fs"
import { fileURLToPath } from "url"
import { dirname, join } from "path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const data = JSON.parse(readFileSync(join(root, "glyphs.json"), "utf8"))
const names = Object.keys(data).sort()
const VARIANTS = ["nerd", "unicode", "emoji"]

const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const upper = (k) => k.toUpperCase().replace(/-/g, "_")
const banner = (c) =>
  [
    `${c} Generated by scripts/generate.mjs from glyphs.json — do not edit by hand.`,
    `${c} Run \`npm run generate\` to regenerate.`,
  ].join("\n")

// Resolve a stored variant value to an actual JS string.
const toChar = (variant, v) =>
  variant === "emoji" ? v : String.fromCodePoint(parseInt(v, 16))
const codePoints = (s) => [...s].map((c) => c.codePointAt(0))
const tsEscape = (s) =>
  codePoints(s)
    .map((cp) => `\\u{${cp.toString(16).toUpperCase()}}`)
    .join("")
const zshEscape = (s) =>
  "$'" +
  codePoints(s)
    .map((cp) => `\\U${cp.toString(16).toUpperCase().padStart(8, "0")}`)
    .join("") +
  "'"

// --- TypeScript: src/generated.ts ---
const tsEntry = (name) => {
  const entry = data[name]
  const parts = VARIANTS.filter((v) => entry[v] != null).map(
    (v) => `${v}: "${tsEscape(toChar(v, entry[v]))}"`,
  )
  return `  ${camel(name)}: { ${parts.join(", ")} },`
}
const ts = [
  banner("//"),
  "",
  "export const glyphs = {",
  ...names.map(tsEntry),
  "} as const",
  "",
  "export type GlyphName = keyof typeof glyphs",
  'export type Variant = "nerd" | "unicode" | "emoji"',
  "",
].join("\n")
writeFileSync(join(root, "src", "generated.ts"), ts)

// --- zsh: glyphs.plugin.zsh (default install: ICON_ prefix, nerd variant) ---
const zshLines = (prefix, variant) =>
  names
    .filter((n) => data[n][variant] != null)
    .map(
      (n) =>
        `${prefix}_${upper(n)}=${zshEscape(toChar(variant, data[n][variant]))}`,
    )
const zsh = [
  banner("#"),
  "# Source this file for ICON_* variables (Nerd Font glyphs).",
  "# Consumers wanting a different prefix or variant call renderZsh() from the",
  "# published package rather than sourcing this default.",
  "",
  ...zshLines("ICON", "nerd"),
  "",
].join("\n")
writeFileSync(join(root, "glyphs.plugin.zsh"), zsh)

console.log(
  `Generated src/generated.ts and glyphs.plugin.zsh (${names.length} glyphs)`,
)
