#!/usr/bin/env node
// Reads glyphs.json (name -> { nerd?, unicode?, emoji? }) and emits:
//   - src/generated.ts   — typed `glyphs` record, each variant an escaped string
//                          (JS \u{XXXX}, by construction — never raw PUA bytes).
//   - glyphs.plugin.zsh  — a ready-to-source zsh plugin: ICON_* vars, nerd
//                          variant, escapes as $'\U0000XXXX'.
//
// A stored value is either a codepoint hex (nerd/unicode — single scalars, kept
// escape-safe) or a literal emoji string (may be a multi-scalar grapheme
// cluster, emitted verbatim). The prefix is a parameter (default ICON); this
// library names no specific consumer.
import { readFileSync, writeFileSync, mkdirSync } from "fs"
import { fileURLToPath } from "url"
import { dirname, join } from "path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const data = JSON.parse(readFileSync(join(root, "glyphs.json"), "utf8"))
const names = Object.keys(data).sort()
const VARIANTS = ["nerd", "unicode", "emoji"]

const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const upper = (k) => k.toUpperCase().replace(/-/g, "_")
const banner = (c) =>
  [
    `${c} Generated by scripts/generate.mjs from glyphs.json — do not edit by hand.`,
    `${c} Run \`npm run generate\` to regenerate.`,
  ].join("\n")

// Resolve a stored variant value to an actual JS string.
const toChar = (variant, v) =>
  variant === "emoji" ? v : String.fromCodePoint(parseInt(v, 16))
const codePoints = (s) => [...s].map((c) => c.codePointAt(0))
const tsEscape = (s) =>
  codePoints(s)
    .map((cp) => `\\u{${cp.toString(16).toUpperCase()}}`)
    .join("")
const zshEscape = (s) =>
  "$'" +
  codePoints(s)
    .map((cp) => `\\U${cp.toString(16).toUpperCase().padStart(8, "0")}`)
    .join("") +
  "'"

// --- TypeScript: src/generated.ts ---
const tsEntry = (name) => {
  const entry = data[name]
  const parts = VARIANTS.filter((v) => entry[v] != null).map(
    (v) => `${v}: "${tsEscape(toChar(v, entry[v]))}"`,
  )
  return `  ${camel(name)}: { ${parts.join(", ")} },`
}
const ts = [
  banner("//"),
  "",
  "export const glyphs = {",
  ...names.map(tsEntry),
  "} as const",
  "",
  "export type GlyphName = keyof typeof glyphs",
  'export type Variant = "nerd" | "unicode" | "emoji"',
  "",
].join("\n")
writeFileSync(join(root, "src", "generated.ts"), ts)

// --- zsh: per-variant ICON_ files + default plugin entrypoint ---
// The zsh/ files let a consumer text-substitute the ICON_ prefix into its own
// namespace (e.g. shui: `sed 's/^ICON_/SHUI_ICON_/'`) without running node —
// values stay escape-safe by construction. `full` emits every name (empty where
// the variant is absent) so cross-set parity is preserved downstream; the thin
// unicode set emits only the glyphs that carry a plain-Unicode fallback.
mkdirSync(join(root, "zsh"), { recursive: true })

const zshVar = (variant, n) => {
  const v = data[n][variant]
  return `ICON_${upper(n)}=${v != null ? zshEscape(toChar(variant, v)) : "''"}`
}
const zshFile = (variant, full, blurb) =>
  [
    banner("#"),
    `# ICON_* variables — ${blurb}`,
    "",
    ...names
      .filter((n) => full || data[n][variant] != null)
      .map((n) => zshVar(variant, n)),
    "",
  ].join("\n")

writeFileSync(
  join(root, "zsh", "nerd.zsh"),
  zshFile("nerd", true, "Nerd Font glyphs (requires a Nerd Font)."),
)
writeFileSync(
  join(root, "zsh", "emoji.zsh"),
  zshFile(
    "emoji",
    true,
    "Unicode emoji; empty where a glyph has no emoji equivalent.",
  ),
)
writeFileSync(
  join(root, "zsh", "unicode.zsh"),
  zshFile("unicode", false, "plain-Unicode fallbacks (geometric shapes only)."),
)

// glyphs.plugin.zsh — default entrypoint for zsh plugin managers (nerd, ICON_).
const plugin = [
  banner("#"),
  "# Default entrypoint: Nerd Font glyphs as ICON_* variables.",
  "# Other variants live in zsh/<variant>.zsh; for a custom prefix, text-",
  "# substitute ICON_ (e.g. sed 's/^ICON_/MYPREFIX_ICON_/').",
  "",
  'source "${0:A:h}/zsh/nerd.zsh"',
  "",
].join("\n")
writeFileSync(join(root, "glyphs.plugin.zsh"), plugin)

console.log(
  `Generated src/generated.ts, glyphs.plugin.zsh, zsh/{nerd,emoji,unicode}.zsh (${names.length} glyphs)`,
)
