# Generated by scripts/generate.mjs from glyphs.json — do not edit by hand.
# Run `npm run generate` to regenerate.
# ICON_* variables — plain-Unicode fallbacks (geometric shapes only).

ICON_BULLET=$'\U0000203A'
ICON_CIRCLE=$'\U000025CF'
ICON_CIRCLE_EMPTY=$'\U000025CB'
ICON_DIAMOND=$'\U000025C6'
ICON_POINTER=$'\U0000276F'
ICON_SQUARE=$'\U000025A0'
ICON_SQUARE_EMPTY=$'\U000025A1'
ICON_TRIANGLE=$'\U000025B2'
